export enum BannerTypeCodes {
    MAIN_BANNER = 'MAIN_BANNER',
    MAIN_POP_UP_BANNER = 'MAIN_POP_UP_BANNER',
    MAIN_POP_UP_NOTIFICATION_BANNER = 'MAIN_POP_UP_NOTIFICATION_BANNER',
    MAIN_MIDDLE_BAND_BANNER = 'MAIN_MIDDLE_BAND_BANNER'
}

export enum LinkType {
    INTERNAL = 'INTERNAL',
    EXTERNAL = 'EXTERNAL'
}

export enum ContentType {
    POST = 'POST',
    MAGAZINE = 'MAGAZINE',
    QNA = 'QNA',
    MISSION = 'MISSION',
    MY_HOME = 'MYHOME',
    RANKING = 'RANKING',
    SETTING = 'SETTING',
    NOTIFICATION = 'NOTIFICATION',
    AB = 'AB',
    PRODUCT = 'PRODUCT',
    MAGAZINE_HOME = 'MAGAZINE_HOME',
    MISSION_HOME = 'MISSION_HOME',
    QNA_HOME = 'QNA_HOME',
    QNA_LIST = 'QNA_LIST',
    AB_LIST = 'AB_LIST',
    POST_HOME = 'POST_HOME',
    NOTICE = 'NOTICE'
}
